backend:
  name: git-gateway
  repo: moustaphad530-dot/site-mancs
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/4cbb053a-85bf-4696-bd5f-592dc2c4d70e/pkce
  auth_token_endpoint: /sites/4cbb053a-85bf-4696-bd5f-592dc2c4d70e/token
  gateway_url: https://gateway.decapbridge.com
